[[Exodus]]
arch = "aarch64"
git-tree-sha1 = "18da22175675e72834bf24776cb088e3781c524e"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "bad8cec31a807e602bd5affa3c7ebd108c4168ae30567b5cecdc2d7c62072c4b"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v0.1.4+0/Exodus.v0.1.4.aarch64-linux-gnu.tar.gz"
[[Exodus]]
arch = "i686"
git-tree-sha1 = "2fea288f5c04cc20ca907a870fcf94cc975a7f8e"
os = "windows"

    [[Exodus.download]]
    sha256 = "59cc57c866e7db0184139d21633d6e075ad411d3461ee741be95b5a0bf604661"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v0.1.4+0/Exodus.v0.1.4.i686-w64-mingw32.tar.gz"
[[Exodus]]
arch = "x86_64"
git-tree-sha1 = "d51ec410334b8f23e43e1477fecc993f27ed67e0"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "dcefa2c1335ca2c28ced8746b31ea3d608125fcf77ddc9e9303a3e37f6efc3b9"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v0.1.4+0/Exodus.v0.1.4.x86_64-linux-gnu.tar.gz"
[[Exodus]]
arch = "x86_64"
git-tree-sha1 = "e58af70bbec88b30768a98c35cd82530171da0c7"
os = "windows"

    [[Exodus.download]]
    sha256 = "ae688198c109309d6a9cd0cc090f6f07c9bb6f98ce10fcef8380af4a3ea014ed"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v0.1.4+0/Exodus.v0.1.4.x86_64-w64-mingw32.tar.gz"
[[Exodus]]
arch = "aarch64"
git-tree-sha1 = "a80dd849a9924a43293af9fde027eefdd9a66e39"
os = "macos"

    [[Exodus.download]]
    sha256 = "aff2da3f4e391ea206797b1da0a664ec66bfd5f0932b6c6f4ca72b8111be26ee"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v8.19.0+1/Exodus.v8.19.0.aarch64-apple-darwin.tar.gz"
[[Exodus]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7eae1cf2f524b26ab27428f7634e104bde766d2"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "48243292250605098dcbfea2a2e1a8396b46c6c89a618fd7f245e222e576c171"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v8.19.0+1/Exodus.v8.19.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Exodus]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f8016b2242863138ea080700e64c02f1fa4aa40"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "328ce928bdc00d3e4a76f6e23cd2144f420bba0cd8909ad40f4a787f3d813438"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v8.19.0+1/Exodus.v8.19.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Exodus]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2ea1a4fd638d8ddf2fc935ab8554610ae1c5529"
os = "windows"

    [[Exodus.download]]
    sha256 = "07769735b96e1fa2a52cce2a5283be73b4cf5c51422019eaef320c9c3ec39d94"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v8.19.0+1/Exodus.v8.19.0.i686-w64-mingw32-cxx03.tar.gz"
[[Exodus]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63158e4eac02378a502ae9e2ff127cf935e020a1"
os = "windows"

    [[Exodus.download]]
    sha256 = "e123d9de36b81e7596fd54d1aa46484bffd74eed2b21a0fa2435e4e239ba1bef"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v8.19.0+1/Exodus.v8.19.0.i686-w64-mingw32-cxx11.tar.gz"
[[Exodus]]
arch = "x86_64"
git-tree-sha1 = "d138f80881beaa9d152ac50963d802ae7e659fda"
os = "macos"

    [[Exodus.download]]
    sha256 = "7fcb2537028de1c8b434acbc98378144c15f11418ec449cdcc484305cd3f1166"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v8.19.0+1/Exodus.v8.19.0.x86_64-apple-darwin.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f9fd8ede8d639cc53e60d9db2698e03bb86e7a3"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "946222be44645786cf88ef441f90ac0c5fb621b78dc45b1972703fb18d75a889"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v8.19.0+1/Exodus.v8.19.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03345b4ac567ff13961daf11b2b8e726e8148c48"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "703265b46066923299ac7de3990eee91997a2fb860fac1d321abc94760a08333"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v8.19.0+1/Exodus.v8.19.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e3084ceede602603fbb3b06e26e3dbf96f65bee"
os = "windows"

    [[Exodus.download]]
    sha256 = "c3fe5aab9d724b81506cefbf5fab1104a0bf1e2ad71b700d5bd7c20f69d4727b"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v8.19.0+1/Exodus.v8.19.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Exodus]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "143aa8a3577df5634af2a13c4685902880d0b75c"
os = "windows"

    [[Exodus.download]]
    sha256 = "6f09611374b224a5fee6d5b5f2a97ba31316f77f76efb83b5e8dc47c250b94c7"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v8.19.0+1/Exodus.v8.19.0.x86_64-w64-mingw32-cxx11.tar.gz"
