[[Exodus]]
arch = "aarch64"
git-tree-sha1 = "e1ef4f645f4ffe7d39ca53df117fa134f97cf89b"
os = "macos"

    [[Exodus.download]]
    sha256 = "4e5fb18e2cb7c1b2f366bc8b786175284b1c1dc8cd671f4c122a9de52a22d96f"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v0.1.4+0/Exodus.v0.1.4.aarch64-apple-darwin.tar.gz"
[[Exodus]]
arch = "aarch64"
git-tree-sha1 = "18da22175675e72834bf24776cb088e3781c524e"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "bad8cec31a807e602bd5affa3c7ebd108c4168ae30567b5cecdc2d7c62072c4b"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v0.1.4+0/Exodus.v0.1.4.aarch64-linux-gnu.tar.gz"
[[Exodus]]
arch = "i686"
git-tree-sha1 = "2fea288f5c04cc20ca907a870fcf94cc975a7f8e"
os = "windows"

    [[Exodus.download]]
    sha256 = "59cc57c866e7db0184139d21633d6e075ad411d3461ee741be95b5a0bf604661"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v0.1.4+0/Exodus.v0.1.4.i686-w64-mingw32.tar.gz"
[[Exodus]]
arch = "x86_64"
git-tree-sha1 = "d438e09b33b0f935ea7a733bf7e450dfcd8ceaf3"
os = "macos"

    [[Exodus.download]]
    sha256 = "2ddc6f168d16129bcb94468aa85bafcd5013a1a65c6f56d14434a8c7789e224e"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v0.1.4+0/Exodus.v0.1.4.x86_64-apple-darwin.tar.gz"
[[Exodus]]
arch = "x86_64"
git-tree-sha1 = "d51ec410334b8f23e43e1477fecc993f27ed67e0"
libc = "glibc"
os = "linux"

    [[Exodus.download]]
    sha256 = "dcefa2c1335ca2c28ced8746b31ea3d608125fcf77ddc9e9303a3e37f6efc3b9"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v0.1.4+0/Exodus.v0.1.4.x86_64-linux-gnu.tar.gz"
[[Exodus]]
arch = "x86_64"
git-tree-sha1 = "e58af70bbec88b30768a98c35cd82530171da0c7"
os = "windows"

    [[Exodus.download]]
    sha256 = "ae688198c109309d6a9cd0cc090f6f07c9bb6f98ce10fcef8380af4a3ea014ed"
    url = "https://github.com/cmhamel/Exodus_jll/releases/download/Exodus-v0.1.4+0/Exodus.v0.1.4.x86_64-w64-mingw32.tar.gz"
